import mongoose from "mongoose";

import { connectDatabase } from "../src/config/db";
import { ProductModel, type Product } from "../src/modules/products/product.model";

const brand = "TechNova";

const imageFor = (slug: string): string =>
  `https://placehold.co/900x600?text=${encodeURIComponent(slug)}`;

const product = (data: Product): Product => data;

const products: Product[] = [
  product({
    name: "DevBook Air 14",
    slug: "devbook-air-14",
    category: "laptop",
    description:
      "A thin and efficient 14-inch laptop tuned for students, web development, note taking, and long battery life on campus or commute days.",
    shortDescription: "Portable student laptop for web development and all-day work.",
    price: 54999,
    originalPrice: 59999,
    stock: 42,
    image: imageFor("DevBook Air 14"),
    images: [imageFor("DevBook Air 14 front"), imageFor("DevBook Air 14 side")],
    brand,
    tags: ["web-development", "student", "portable", "battery", "productivity"],
    specifications: {
      processor: "Intel Core i5-13420H",
      ram: "16GB LPDDR5",
      storage: "512GB NVMe SSD",
      display: "14-inch FHD IPS, 300 nits",
      graphics: "Intel UHD integrated graphics",
      battery: "62Wh, up to 11 hours",
      weight: "1.28 kg",
      operatingSystem: "Windows 11 Home",
      connectivity: "Wi-Fi 6, Bluetooth 5.3, 2x USB-C, HDMI",
    },
    useCases: ["students", "web development", "portability", "battery life"],
    rating: 4.4,
    reviewCount: 214,
    featured: true,
    active: true,
  }),
  product({
    name: "DevBook Pro 14",
    slug: "devbook-pro-14",
    category: "laptop",
    description:
      "A balanced professional coding machine with extra CPU headroom, a color-accurate screen, and battery life suitable for full-stack development.",
    shortDescription: "Professional 14-inch laptop for full-stack development.",
    price: 64999,
    originalPrice: 69999,
    stock: 35,
    image: imageFor("DevBook Pro 14"),
    images: [imageFor("DevBook Pro 14 front"), imageFor("DevBook Pro 14 keyboard")],
    brand,
    tags: ["full-stack", "web-development", "productivity", "battery", "performance"],
    specifications: {
      processor: "AMD Ryzen 7 7840U",
      ram: "16GB DDR5",
      storage: "1TB NVMe SSD",
      display: "14-inch 2.2K IPS, 100% sRGB",
      graphics: "AMD Radeon 780M integrated graphics",
      battery: "70Wh, up to 10 hours",
      weight: "1.36 kg",
      operatingSystem: "Windows 11 Pro",
      connectivity: "Wi-Fi 6E, Bluetooth 5.3, USB4, HDMI 2.1",
    },
    useCases: ["full-stack development", "professional coding", "productivity", "strong battery life"],
    rating: 4.6,
    reviewCount: 186,
    featured: true,
    active: true,
  }),
  product({
    name: "NeuralBook X15",
    slug: "neuralbook-x15",
    category: "laptop",
    description:
      "A performance-focused 15-inch laptop for Python notebooks, local model experiments, containers, and heavier development workloads.",
    shortDescription: "AI/ML-ready laptop with strong CPU and RTX acceleration.",
    price: 69999,
    originalPrice: 76999,
    stock: 27,
    image: imageFor("NeuralBook X15"),
    images: [imageFor("NeuralBook X15 front"), imageFor("NeuralBook X15 ports")],
    brand,
    tags: ["ai-development", "machine-learning", "python", "performance", "full-stack"],
    specifications: {
      processor: "Intel Core i7-13620H",
      ram: "16GB DDR5, expandable to 32GB",
      storage: "1TB NVMe SSD",
      display: "15.6-inch FHD IPS, 144Hz",
      graphics: "NVIDIA GeForce RTX 4050 6GB",
      battery: "58Wh, up to 6.5 hours",
      weight: "1.95 kg",
      operatingSystem: "Windows 11 Home",
      connectivity: "Wi-Fi 6, Bluetooth 5.2, USB-C, HDMI 2.1, RJ45",
    },
    useCases: ["AI/ML development", "Python", "heavier development workloads", "performance"],
    rating: 4.5,
    reviewCount: 143,
    featured: true,
    active: true,
  }),
  product({
    name: "CreatorCore 16",
    slug: "creatorcore-16",
    category: "laptop",
    description:
      "A large-display creator laptop for multitasking, editing timelines, design tools, and development work that benefits from screen space.",
    shortDescription: "16-inch creator and development laptop with a large display.",
    price: 74999,
    originalPrice: 82999,
    stock: 22,
    image: imageFor("CreatorCore 16"),
    images: [imageFor("CreatorCore 16 display"), imageFor("CreatorCore 16 workspace")],
    brand,
    tags: ["creator", "productivity", "performance", "full-stack", "multitasking"],
    specifications: {
      processor: "AMD Ryzen 7 8845HS",
      ram: "32GB DDR5",
      storage: "1TB NVMe SSD",
      display: "16-inch 2.5K IPS, 100% sRGB",
      graphics: "NVIDIA GeForce RTX 3050 6GB",
      battery: "76Wh, up to 8 hours",
      weight: "1.82 kg",
      operatingSystem: "Windows 11 Pro",
      connectivity: "Wi-Fi 6E, Bluetooth 5.3, USB-C PD, HDMI, SD card reader",
    },
    useCases: ["content creation", "development", "large display", "multitasking"],
    rating: 4.7,
    reviewCount: 98,
    featured: true,
    active: true,
  }),
  product({
    name: "GameForge G15",
    slug: "gameforge-g15",
    category: "laptop",
    description:
      "A high-performance gaming laptop with strong GPU power for competitive gaming, CUDA experiments, and demanding local workloads.",
    shortDescription: "Gaming and ML laptop with the strongest GPU in the range.",
    price: 79999,
    originalPrice: 89999,
    stock: 18,
    image: imageFor("GameForge G15"),
    images: [imageFor("GameForge G15 front"), imageFor("GameForge G15 cooling")],
    brand,
    tags: ["gaming", "performance", "ai-development", "machine-learning", "gpu-heavy"],
    specifications: {
      processor: "Intel Core i7-14650HX",
      ram: "16GB DDR5, expandable to 64GB",
      storage: "1TB NVMe SSD",
      display: "15.6-inch QHD IPS, 165Hz",
      graphics: "NVIDIA GeForce RTX 4060 8GB",
      battery: "60Wh, up to 5 hours",
      weight: "2.35 kg",
      operatingSystem: "Windows 11 Home",
      connectivity: "Wi-Fi 6E, Bluetooth 5.3, USB-C, HDMI 2.1, RJ45",
    },
    useCases: ["gaming", "GPU-heavy workloads", "AI experiments", "performance"],
    rating: 4.6,
    reviewCount: 121,
    featured: true,
    active: true,
  }),
  product({
    name: "BudgetCode 14",
    slug: "budgetcode-14",
    category: "laptop",
    description:
      "An affordable coding laptop for first-year students, beginner developers, browser-based learning, and everyday assignments.",
    shortDescription: "Budget-friendly laptop for beginner programming.",
    price: 44999,
    originalPrice: 49999,
    stock: 58,
    image: imageFor("BudgetCode 14"),
    images: [imageFor("BudgetCode 14 front"), imageFor("BudgetCode 14 desk")],
    brand,
    tags: ["budget", "student", "web-development", "portable", "productivity"],
    specifications: {
      processor: "Intel Core i3-1315U",
      ram: "8GB DDR4, expandable to 16GB",
      storage: "512GB NVMe SSD",
      display: "14-inch FHD anti-glare",
      graphics: "Intel UHD integrated graphics",
      battery: "50Wh, up to 8 hours",
      weight: "1.42 kg",
      operatingSystem: "Windows 11 Home",
      connectivity: "Wi-Fi 6, Bluetooth 5.1, USB-C, HDMI",
    },
    useCases: ["beginner developers", "college students", "basic programming", "budget-conscious customers"],
    rating: 4.2,
    reviewCount: 267,
    featured: false,
    active: true,
  }),
  product({
    name: "ViewDock 24 Productivity Monitor",
    slug: "viewdock-24-productivity-monitor",
    category: "monitor",
    description:
      "An affordable 24-inch monitor for spreadsheets, documentation, coding, and dual-screen productivity setups.",
    shortDescription: "Affordable 24-inch FHD productivity monitor.",
    price: 9999,
    originalPrice: 11999,
    stock: 64,
    image: imageFor("ViewDock 24 Productivity Monitor"),
    images: [imageFor("ViewDock 24 front"), imageFor("ViewDock 24 side")],
    brand,
    tags: ["productivity", "budget", "web-development", "student"],
    specifications: {
      display: "24-inch FHD IPS",
      refreshRate: "75Hz",
      colorCoverage: "99% sRGB",
      ports: "HDMI, VGA, audio out",
      ergonomics: "Tilt adjustment",
    },
    useCases: ["office productivity", "coding", "study desks", "dual-monitor setups"],
    rating: 4.3,
    reviewCount: 312,
    featured: false,
    active: true,
  }),
  product({
    name: "PixelWide 27 Creator Monitor",
    slug: "pixelwide-27-creator-monitor",
    category: "monitor",
    description:
      "A premium 27-inch 4K creator and developer monitor with sharp text, wide color coverage, and USB-C docking.",
    shortDescription: "Premium 27-inch 4K monitor for creators and developers.",
    price: 32999,
    originalPrice: 37999,
    stock: 21,
    image: imageFor("PixelWide 27 Creator Monitor"),
    images: [imageFor("PixelWide 27 front"), imageFor("PixelWide 27 ports")],
    brand,
    tags: ["creator", "productivity", "full-stack", "performance"],
    specifications: {
      display: "27-inch 4K IPS",
      refreshRate: "60Hz",
      colorCoverage: "100% sRGB, 95% DCI-P3",
      ports: "USB-C 90W PD, HDMI 2.1, DisplayPort, USB hub",
      ergonomics: "Height, tilt, swivel, pivot",
    },
    useCases: ["content creation", "software development", "large workspaces", "color-sensitive work"],
    rating: 4.7,
    reviewCount: 89,
    featured: true,
    active: true,
  }),
  product({
    name: "TypeFlex Mini Wireless Keyboard",
    slug: "typeflex-mini-wireless-keyboard",
    category: "keyboard",
    description:
      "A compact wireless keyboard for clean desks, travel setups, and quiet productivity across multiple devices.",
    shortDescription: "Compact wireless keyboard for productivity.",
    price: 2499,
    originalPrice: 2999,
    stock: 93,
    image: imageFor("TypeFlex Mini Wireless Keyboard"),
    images: [imageFor("TypeFlex Mini top"), imageFor("TypeFlex Mini angle")],
    brand,
    tags: ["productivity", "portable", "student", "battery"],
    specifications: {
      layout: "75% compact layout",
      switches: "Low-profile scissor switches",
      connectivity: "Bluetooth 5.2 and 2.4GHz dongle",
      battery: "Up to 4 months",
      compatibility: "Windows, macOS, Linux, Android",
    },
    useCases: ["portable workstations", "office productivity", "student desks", "multi-device typing"],
    rating: 4.4,
    reviewCount: 176,
    featured: false,
    active: true,
  }),
  product({
    name: "MechStrike RGB TKL Keyboard",
    slug: "mechstrike-rgb-tkl-keyboard",
    category: "keyboard",
    description:
      "A tenkeyless mechanical keyboard with hot-swappable switches, low-latency wired mode, and per-key RGB for developers and gamers.",
    shortDescription: "Mechanical TKL keyboard for coding and gaming.",
    price: 5999,
    originalPrice: 6999,
    stock: 47,
    image: imageFor("MechStrike RGB TKL Keyboard"),
    images: [imageFor("MechStrike RGB top"), imageFor("MechStrike RGB lighting")],
    brand,
    tags: ["gaming", "web-development", "performance", "productivity"],
    specifications: {
      layout: "Tenkeyless 87-key",
      switches: "Hot-swappable tactile mechanical switches",
      connectivity: "USB-C wired",
      lighting: "Per-key RGB",
      pollingRate: "1000Hz",
    },
    useCases: ["software development", "gaming", "desk setups", "fast typing"],
    rating: 4.5,
    reviewCount: 203,
    featured: false,
    active: true,
  }),
  product({
    name: "FlowPoint Ergo Mouse",
    slug: "flowpoint-ergo-mouse",
    category: "mouse",
    description:
      "An ergonomic productivity mouse with silent clicks, horizontal scrolling, and long battery life for daily work.",
    shortDescription: "Ergonomic wireless mouse for productivity.",
    price: 1999,
    originalPrice: 2499,
    stock: 118,
    image: imageFor("FlowPoint Ergo Mouse"),
    images: [imageFor("FlowPoint Ergo side"), imageFor("FlowPoint Ergo desk")],
    brand,
    tags: ["productivity", "battery", "budget", "portable"],
    specifications: {
      sensor: "4000 DPI optical sensor",
      connectivity: "Bluetooth and 2.4GHz dongle",
      battery: "Up to 12 months",
      buttons: "6 programmable buttons",
      ergonomics: "Right-handed contoured grip",
    },
    useCases: ["office productivity", "coding", "spreadsheet work", "travel setups"],
    rating: 4.3,
    reviewCount: 241,
    featured: false,
    active: true,
  }),
  product({
    name: "RapidAim Pro Mouse",
    slug: "rapidaim-pro-mouse",
    category: "mouse",
    description:
      "A lightweight performance mouse with a high-DPI sensor, low-latency wireless mode, and fast response for gaming and precision work.",
    shortDescription: "High-performance wireless gaming mouse.",
    price: 4499,
    originalPrice: 5499,
    stock: 52,
    image: imageFor("RapidAim Pro Mouse"),
    images: [imageFor("RapidAim Pro top"), imageFor("RapidAim Pro sensor")],
    brand,
    tags: ["gaming", "performance", "productivity"],
    specifications: {
      sensor: "26000 DPI optical sensor",
      connectivity: "2.4GHz low-latency wireless and USB-C",
      battery: "Up to 80 hours",
      weight: "72 g",
      pollingRate: "1000Hz",
    },
    useCases: ["gaming", "design precision", "high-refresh setups", "performance work"],
    rating: 4.6,
    reviewCount: 137,
    featured: false,
    active: true,
  }),
  product({
    name: "CodeTune Lite Headphones",
    slug: "codetune-lite-headphones",
    category: "headphones",
    description:
      "Affordable over-ear headphones with a comfortable fit and clear microphone for study sessions, calls, and focused coding.",
    shortDescription: "Affordable headphones for work, calls, and coding.",
    price: 2999,
    originalPrice: 3499,
    stock: 76,
    image: imageFor("CodeTune Lite Headphones"),
    images: [imageFor("CodeTune Lite front"), imageFor("CodeTune Lite mic")],
    brand,
    tags: ["budget", "productivity", "student", "web-development"],
    specifications: {
      driver: "40mm dynamic drivers",
      connectivity: "Bluetooth 5.3 and AUX",
      battery: "Up to 35 hours",
      microphone: "Detachable boom mic",
      noiseControl: "Passive noise isolation",
    },
    useCases: ["developer calls", "online classes", "focus work", "budget audio"],
    rating: 4.2,
    reviewCount: 194,
    featured: false,
    active: true,
  }),
  product({
    name: "QuietFlow ANC Pro Headphones",
    slug: "quietflow-anc-pro-headphones",
    category: "headphones",
    description:
      "Premium noise-cancelling headphones for deep work, travel, and long development sessions in noisy environments.",
    shortDescription: "Premium ANC headphones for deep focus.",
    price: 14999,
    originalPrice: 17999,
    stock: 33,
    image: imageFor("QuietFlow ANC Pro Headphones"),
    images: [imageFor("QuietFlow ANC Pro side"), imageFor("QuietFlow ANC Pro case")],
    brand,
    tags: ["productivity", "battery", "premium", "portable"],
    specifications: {
      driver: "45mm custom dynamic drivers",
      connectivity: "Bluetooth 5.3 with multipoint",
      battery: "Up to 45 hours with ANC",
      microphone: "Beamforming mic array",
      noiseControl: "Hybrid active noise cancellation",
    },
    useCases: ["deep work", "travel", "remote meetings", "long coding sessions"],
    rating: 4.8,
    reviewCount: 112,
    featured: true,
    active: true,
  }),
  product({
    name: "PortStack USB-C Developer Hub",
    slug: "portstack-usb-c-developer-hub",
    category: "accessory",
    description:
      "A compact USB-C hub that expands a developer laptop with HDMI, Ethernet, card reading, and power delivery.",
    shortDescription: "USB-C hub with HDMI, Ethernet, and 100W passthrough.",
    price: 3499,
    originalPrice: 4299,
    stock: 88,
    image: imageFor("PortStack USB-C Developer Hub"),
    images: [imageFor("PortStack USB-C ports"), imageFor("PortStack USB-C laptop")],
    brand,
    tags: ["productivity", "web-development", "portable", "full-stack"],
    specifications: {
      ports: "HDMI 4K, RJ45, 2x USB-A, USB-C PD, SD, microSD",
      powerDelivery: "Up to 100W passthrough",
      material: "Aluminium shell",
      compatibility: "Windows, macOS, Linux, Android",
      weight: "92 g",
    },
    useCases: ["developer desks", "presentations", "travel workstations", "multi-device connectivity"],
    rating: 4.5,
    reviewCount: 158,
    featured: false,
    active: true,
  }),
  product({
    name: "CoolLift Pro Laptop Stand",
    slug: "coollift-pro-laptop-stand",
    category: "accessory",
    description:
      "An adjustable aluminium laptop stand with active cooling for better ergonomics and sustained performance during long work sessions.",
    shortDescription: "Adjustable cooling stand for laptops.",
    price: 2799,
    originalPrice: 3299,
    stock: 71,
    image: imageFor("CoolLift Pro Laptop Stand"),
    images: [imageFor("CoolLift Pro angle"), imageFor("CoolLift Pro cooling")],
    brand,
    tags: ["productivity", "performance", "creator", "gaming"],
    specifications: {
      material: "Aluminium alloy",
      cooling: "Dual silent fans with three speed levels",
      compatibility: "11-inch to 17-inch laptops",
      adjustment: "7 height levels",
      weight: "780 g",
    },
    useCases: ["ergonomic desks", "gaming laptops", "creator laptops", "thermal management"],
    rating: 4.4,
    reviewCount: 129,
    featured: false,
    active: true,
  }),
];

const seedProducts = async (): Promise<void> => {
  try {
    await connectDatabase();

    const deleteResult = await ProductModel.deleteMany({ brand });
    const insertedProducts = await ProductModel.insertMany(products, {
      ordered: true,
    });

    console.log(`Removed ${deleteResult.deletedCount} existing ${brand} products.`);
    console.log(`Inserted ${insertedProducts.length} ${brand} products.`);
  } catch (error) {
    console.error("Product seeding failed");
    console.error(error);
    process.exitCode = 1;
  } finally {
    await mongoose.connection.close();
  }
};

void seedProducts();
